###
GET http://localhost:3000/api/clientes

###
GET http://localhost:3000/api/clientes/6060afa649a8f32bb05aafec

###
POST  http://localhost:3000/api/clientes
Content-Type: application/json

{
    "nombre": "Test7",
    "apellidos": "Test Test",
    "email": "test7@gmail.com",
    "cuota": 20,
    "activo": true
}
###
PUT http://localhost:3000/api/clientes/6060c049844d921420cced2
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MDYwYzA5Mzg0NGQ5MjE0MmMwY2NlZDMiLCJpYXQiOjE2MTY5NTM0OTEsImV4cCI6MTYxNjk1NDA5MX0.NHmxhny7zXjxc6L0Q0EdgPEPusCQuLKvXLXN3pl1X1w

{
    "nombre": "Test7",
    "apellidos": "Test Test",
    "email": "test7@gmail.com",
    "cuota": 50,
    "activo": true
}

###
DELETE http://localhost:3000/api/clientes/6060c049844d92142c0cced2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MDYwYzA5Mzg0NGQ5MjE0MmMwY2NlZDMiLCJpYXQiOjE2MTY5NTM0OTEsImV4cCI6MTYxNjk1NDA5MX0.NHmxhny7zXjxc6L0Q0EdgPEPusCQuLKvXLXN3pl1X1w

###
POST  http://localhost:3000/api/usuarios/registro
Content-Type: application/json

{
    "username": "Test10",
    "email": "test10@gmail.com",
    "password": "password1",
    "rol": "admin"
}

###
POST  http://localhost:3000/api/usuarios/login
Content-Type: application/json

{
    "email": "test10@gmail.com",
    "password": "password1"
}

